# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-07 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='modification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
